##===----------------------------------------------------------------------===##
#
# This file is Modular Inc proprietary.
#
##===----------------------------------------------------------------------===##

name: bench_mha
file: $KERNEL_BENCHMARKS_ROOT/gpu/bench_mha.mojo

params:

# Llama3 shapes with increasing batch size and sequence length.
- mask_rank: 4
  qkv_type: DType.bfloat16
  mask_type: DType.bfloat16
  depth: 128
  num_heads: 32
  group: 4
  $seq_len: 1
  batch_size: [4, 16, 32, 64, 128, 256]
  $num_keys: [32, 64, 128, 256, 512, 1024, 1536, 2048]
